#!/usr/bin/env python

from pyprocessing import *

import sys

if len(sys.argv) > 1:
    filename = sys.argv[1]
    del sys.argv[1] # Remove second argument from sys.argv

    exec(open(filename).read())
    run()
else:
    print('Usage:')
    print('pyprocessing pythonfile.py')
